Bmonteir Module02
SEAME-pt/Team06-SEAME-warm-up pull request #15
Opened 2024-11-13 17:03 UTC by BelmiroRodrigues

2024-11-13 17:19 UTC, Lrosa-do-seame approved these changes

2024-11-13 17:20 UTC, Lrosa-do-seame submitted a review, later dismissed

2024-11-14 08:49 UTC, SomeMedtnerGuy requested changes
Podes sff pôr o código na pasta do módulo? De resto parece-me fixe (do pouco que ainda percebo :smiling_face_with_tear: )
Uma outra coisa, para já não necessária para aprovação: Talvez seja porreiro incluir o .vscode num .gitignore? Ou isso ou temos que definir uma configuração para todos, para a pasta não estar sempre a ser alterada.)

2024-11-14 10:36 UTC, SomeMedtnerGuy approved these changes, later dismissed

2024-11-14 14:18 UTC, Lrosa-do-seame submitted a review, later dismissed

2024-11-14 15:51 UTC, zeira42 commented
Checks are not successful...

2024-11-15 10:22 UTC, SomeMedtnerGuy approved these changes
Checks now work!

2024-11-15 13:31 UTC, zeira42 approved these changes
Well done, interesting exercise, looking forward to code this myself!

2024-11-15 15:05 UTC, Lrosa-do-seame approved these changes

2024-11-15 15:08 UTC, merged